[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$RunDirectory,
    [Parameter(Mandatory=$true)][string]$OutputPath
)
$ErrorActionPreference='Stop';$reasons=New-Object 'System.Collections.Generic.List[string]'
function Add-Reason{param([string]$Code);if(-not$reasons.Contains($Code)){[void]$reasons.Add($Code)}}
function Read-Json{param([string]$Path);try{$e=New-Object System.Text.UTF8Encoding($false,$true);return [IO.File]::ReadAllText($Path,$e)|ConvertFrom-Json}catch{return $null}}
function Within{param([string]$Path,[string]$Root);$p=[IO.Path]::GetFullPath($Path).TrimEnd('\');$r=[IO.Path]::GetFullPath($Root).TrimEnd('\');return $p.Equals($r,[StringComparison]::OrdinalIgnoreCase)-or$p.StartsWith($r+'\',[StringComparison]::OrdinalIgnoreCase)}
function Write-CreateOnly{param([string]$Path,[string]$Content);$dir=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $dir -PathType Container)){New-Item -ItemType Directory -Path $dir -Force|Out-Null};$s=[IO.File]::Open($Path,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);try{$b=[Text.Encoding]::UTF8.GetBytes($Content);$s.Write($b,0,$b.Length)}finally{$s.Dispose()}}
function Write-Invalid{param($Payload);$result=[ordered]@{schema_version=1;valid=$false;reason_codes=@($reasons);project=$null;run=$null;engineering=$null;installation=[ordered]@{status='NOT_VERIFIED'};real_use=[ordered]@{status='NOT_RUN'};human_acceptance=[ordered]@{status='PENDING';signoff=''};formal_release=[ordered]@{status='NO_GO'};known_failures=@();blockers=@();rollback='Restore the pre-run evidence and source commit; do not alter the original worktree.'};$result|ConvertTo-Json -Depth 20;exit 1}
$root=[IO.Path]::GetFullPath($RunDirectory);$output=[IO.Path]::GetFullPath($OutputPath)
if(-not(Test-Path -LiteralPath $root -PathType Container)){Add-Reason 'RUN_DIRECTORY_MISSING';Write-Invalid $null}
if(-not(Within $output $root)){Add-Reason 'OUTPUT_OUTSIDE_RUN_DIRECTORY';Write-Invalid $null}
$manifestPath=Join-Path $root 'run-manifest.json';$statePath=Join-Path $root 'state.json';$cpDir=Join-Path $root 'checkpoints'
if(-not(Test-Path -LiteralPath $manifestPath -PathType Leaf)){Add-Reason 'MANIFEST_MISSING';Write-Invalid $null};$manifest=Read-Json $manifestPath;if($null-eq$manifest){Add-Reason 'MANIFEST_INVALID_JSON';Write-Invalid $null}
if(-not(Test-Path -LiteralPath $statePath -PathType Leaf)){Add-Reason 'STATE_MISSING';Write-Invalid $null};$state=Read-Json $statePath;if($null-eq$state){Add-Reason 'STATE_INVALID_JSON';Write-Invalid $null}
$files=@(Get-ChildItem -LiteralPath $cpDir -Filter 'checkpoint-*.json' -File -ErrorAction SilentlyContinue|Sort-Object Name);if($files.Count-eq 0){Add-Reason 'NO_CHECKPOINT';Write-Invalid $null}
$checkpoints=@();$expected=1;$previousHash=$null;foreach($file in $files){$cp=Read-Json $file.FullName;if($null-eq$cp){Add-Reason 'CHECKPOINT_INVALID_JSON';continue};$checkpoints+=,$cp;if([int]$cp.sequence-ne$expected){Add-Reason 'CHECKPOINT_CHAIN_INVALID'};if([string]$cp.run_id-ne[string]$manifest.run_id){Add-Reason 'CHECKPOINT_CHAIN_INVALID'};if($expected-gt 1-and[string]$cp.previous_checkpoint_sha256-ne[string]$previousHash){Add-Reason 'CHECKPOINT_CHAIN_INVALID'};if([string]::IsNullOrWhiteSpace([string]$cp.checkpoint_sha256)){Add-Reason 'CHECKPOINT_CHAIN_INVALID'};$ev=[string]$cp.evidence_path;if([string]::IsNullOrWhiteSpace($ev)-or-not(Test-Path -LiteralPath $ev -PathType Leaf)){Add-Reason 'MISSING_TASK_EVIDENCE'};$expected++;$previousHash=[string]$cp.checkpoint_sha256}
$known=@($manifest.known_failures);foreach($failure in $known){if($failure.disclosed -ne $true){Add-Reason 'KNOWN_FAILURE_UNDISCLOSED'}}
if($reasons.Count-gt 0){Write-Invalid $null}
$project=[ordered]@{project_root=[string]$manifest.project_root;worktree=[string]$manifest.git.worktree;branch=[string]$manifest.git.branch;head=[string]$manifest.git.head;project_id=[string]$manifest.goal.project_id}
$deliveryTarget=[string]$manifest.delivery_target;$releaseIntent=[string]$manifest.release_intent;$reviewPolicy=[string]$manifest.review_policy;$preflightStatus=[string]$manifest.preflight_status;$resolver=$manifest.resolver
$run=[ordered]@{run_id=[string]$manifest.run_id;model=[string]$manifest.model;reasoning=[string]$manifest.reasoning;design_hash=[string]$manifest.design_hash;plan_hash=[string]$manifest.plan_hash;state=[string]$state.state;delivery_target=$deliveryTarget;release_intent=$releaseIntent;review_policy=$reviewPolicy;preflight_status=$preflightStatus;resolver=$resolver}
$engineering=[ordered]@{status=if([string]::IsNullOrWhiteSpace([string]$state.engineering_status)){'PASS'}else{[string]$state.engineering_status};checkpoint_count=$checkpoints.Count;commands=@($checkpoints|ForEach-Object{[ordered]@{task_id=$_.task_id;command=$_.command;exit_code=$_.exit_code;evidence_path=$_.evidence_path;evidence_sha256=$_.evidence_sha256}})}
$result=[ordered]@{schema_version=1;valid=$true;reason_codes=@();project=$project;run=$run;delivery_target=$deliveryTarget;release_intent=$releaseIntent;review_policy=$reviewPolicy;preflight_status=$preflightStatus;resolver=$resolver;engineering=$engineering;installation=[ordered]@{status='NOT_VERIFIED';hash_parity='PENDING'};real_use=[ordered]@{status='NOT_RUN';receipt=''};human_acceptance=[ordered]@{status='PENDING';reviewer='';signoff='';decision=''};formal_release=[ordered]@{status='NO_GO';authorization=''};known_failures=$known;blockers=@();rollback='Restore the pre-run evidence and source commit; do not alter the original worktree.';generated_at_utc=[DateTime]::UtcNow.ToString('o')}
$json=$result|ConvertTo-Json -Depth 20;$markdown="# Long-Run Closure Input`r`n`r`n- Project: $($project.project_id)`r`n- Run: $($run.run_id)`r`n- Engineering: $($engineering.status)`r`n- Installation: NOT_VERIFIED`r`n- Real use: NOT_RUN`r`n- Human acceptance: PENDING`r`n- Formal release: NO_GO`r`n`r`n## Verification evidence`r`n`r`nCheckpoint count: $($checkpoints.Count)`r`n`r`n## Human review`r`n`r`nReviewer: `r`nSignoff: `r`nDecision: `r`n"
try{Write-CreateOnly -Path $output -Content $json;$md=[IO.Path]::Combine((Split-Path -Parent $output),([IO.Path]::GetFileNameWithoutExtension($output)+'.md'));Write-CreateOnly -Path $md -Content $markdown}catch{Add-Reason 'OUTPUT_CREATE_FAILED';Write-Invalid $null}
$result|ConvertTo-Json -Depth 20;exit 0
