[CmdletBinding()]
param()
$ErrorActionPreference='Stop';$implementation=Join-Path $PSScriptRoot 'New-LongRunClosureInput.ps1'
if(-not(Test-Path -LiteralPath $implementation -PathType Leaf)){Write-Error 'RED: New-LongRunClosureInput.ps1 is missing.';exit 1}
function Assert-Equal{param($Actual,$Expected,[string]$Message);if($Actual-ne$Expected){throw "$Message Expected=[$Expected] Actual=[$Actual]"}}
function Assert-Contains{param([object[]]$Actual,[string]$Expected,[string]$Message);if($Actual-notcontains$Expected){throw "$Message Missing=[$Expected] Actual=[$($Actual-join ',')]"}}
function Invoke-Closure{param([hashtable]$Arguments);$old=$ErrorActionPreference;$ErrorActionPreference='Continue';try{$raw=&powershell.exe -NoProfile -ExecutionPolicy Bypass -File $implementation @Arguments 2>&1;$code=$LASTEXITCODE}finally{$ErrorActionPreference=$old};$lines=@($raw|ForEach-Object{[string]$_});$start=-1;$end=-1;for($i=0;$i-lt$lines.Count;$i++){if($start-lt 0-and$lines[$i].TrimStart().StartsWith('{')){$start=$i};if($lines[$i].TrimEnd().EndsWith('}')){$end=$i}};$json=if($start-ge 0-and$end-ge$start){(($lines[$start..$end]-join [Environment]::NewLine)|ConvertFrom-Json)}else{$null};[pscustomobject]@{Code=$code;Json=$json;Raw=$raw}}
function Write-Json{param([string]$Path,$Object);$Object|ConvertTo-Json -Depth 16|Set-Content -LiteralPath $Path -Encoding utf8}
function New-ValidRun{param([string]$Root);$cpDir=Join-Path $Root 'checkpoints';$eDir=Join-Path $Root 'task-evidence';New-Item -ItemType Directory -Path $cpDir,$eDir -Force|Out-Null;$evidence=Join-Path $eDir 'T01.txt';Set-Content -LiteralPath $evidence -Value 'verified evidence' -Encoding utf8;$manifest=[ordered]@{schema_version=1;valid=$true;run_id='closure-fixture';project_root=$Root;profile_path=(Join-Path $Root 'execution-profile.json');design_hash=('A'*64);plan_hash=('B'*64);model='gpt-5.6-luna';reasoning='xhigh';delivery_target='ENGINEERING_ONLY';release_intent='NONE';review_policy='NONE';preflight_status='READY';resolver=[ordered]@{governance_mode='LOCAL_AUTONOMOUS';terminal_state='LOCAL_CANDIDATE_READY';required_review=$false};git=[ordered]@{root=$Root;worktree=$Root;branch='codex/fixture';head=('1'*40)};goal=[ordered]@{project_id='closure-fixture';implementation_phase='approved-plan';stopping_condition='review'};known_failures=@()};Write-Json -Path (Join-Path $Root 'run-manifest.json') -Object $manifest;Write-Json -Path (Join-Path $Root 'state.json') -Object ([ordered]@{state='REVIEW_PACKAGE';engineering_status='PASS'});$cp=[ordered]@{schema_version=1;run_id='closure-fixture';sequence=1;task_id='T01';command='test';exit_code=0;evidence_path=$evidence;evidence_sha256='hash';checkpoint_sha256='cp-hash';previous_checkpoint_sha256=$null};Write-Json -Path (Join-Path $cpDir 'checkpoint-001.json') -Object $cp;return [pscustomobject]@{Root=$Root;Manifest=(Join-Path $Root 'run-manifest.json');Evidence=$evidence;Checkpoints=$cpDir}}
$base=[System.IO.Path]::GetFullPath('X:\Projects\01_Active\15_项目开发治理Skills\99_Temp\long-run-v1_1\T10');$fixture=Join-Path $base ('closure-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Path $fixture -Force|Out-Null;$run=New-ValidRun -Root $fixture
try{
    $valid=Invoke-Closure -Arguments @{RunDirectory=$run.Root;OutputPath=(Join-Path $run.Root 'closure-input.json')};Assert-Equal $valid.Code 0 'Valid closure input must exit zero.';Assert-Equal $valid.Json.valid $true 'Valid closure.';Assert-Equal $valid.Json.formal_release.status 'NO_GO' 'Formal release default.';Assert-Equal $valid.Json.real_use.status 'NOT_RUN' 'Real use remains separate.';Assert-Equal $valid.Json.human_acceptance.signoff '' 'Human signoff must be blank.';Assert-Equal $valid.Json.delivery_target 'ENGINEERING_ONLY' 'Closure input must bind delivery target.';Assert-Equal $valid.Json.resolver.terminal_state 'LOCAL_CANDIDATE_READY' 'Closure input must bind resolver terminal.';Assert-Equal (Test-Path -LiteralPath (Join-Path $run.Root 'closure-input.md') -PathType Leaf) $true 'Markdown index must be created.'
    Remove-Item -LiteralPath $run.Evidence -Force;$missing=Invoke-Closure -Arguments @{RunDirectory=$run.Root;OutputPath=(Join-Path $run.Root 'missing.json')};Assert-Equal $missing.Code 1 'Missing task evidence must fail.';Assert-Contains @($missing.Json.reason_codes) 'MISSING_TASK_EVIDENCE' 'Missing evidence reason.';Set-Content -LiteralPath $run.Evidence -Value 'restored' -Encoding utf8
    $second=[ordered]@{schema_version=1;run_id='closure-fixture';sequence=2;task_id='T02';command='test';exit_code=0;evidence_path=$run.Evidence;evidence_sha256='hash';checkpoint_sha256='cp-two';previous_checkpoint_sha256='wrong'};Write-Json -Path (Join-Path $run.Checkpoints 'checkpoint-002.json') -Object $second;$broken=Invoke-Closure -Arguments @{RunDirectory=$run.Root;OutputPath=(Join-Path $run.Root 'broken.json')};Assert-Equal $broken.Code 1 'Broken checkpoint chain must fail.';Assert-Contains @($broken.Json.reason_codes) 'CHECKPOINT_CHAIN_INVALID' 'Broken chain reason.';Remove-Item -LiteralPath (Join-Path $run.Checkpoints 'checkpoint-002.json') -Force
    $manifest=Get-Content -LiteralPath $run.Manifest -Raw|ConvertFrom-Json;$manifest.known_failures=@([ordered]@{id='F01';disclosed=$false;summary='hidden failure'});Write-Json -Path $run.Manifest -Object $manifest;$undisclosed=Invoke-Closure -Arguments @{RunDirectory=$run.Root;OutputPath=(Join-Path $run.Root 'undisclosed.json')};Assert-Equal $undisclosed.Code 1 'Undisclosed failure must fail.';Assert-Contains @($undisclosed.Json.reason_codes) 'KNOWN_FAILURE_UNDISCLOSED' 'Undisclosed failure reason.'
    Write-Output 'TEST_LONG_RUN_CLOSURE_INPUT=PASS';exit 0
}finally{if(Test-Path -LiteralPath $fixture){Remove-Item -LiteralPath $fixture -Recurse -Force}}
