[CmdletBinding()]
param()
$ErrorActionPreference='Stop';$implementation=Join-Path $PSScriptRoot 'Resolve-LongRunResume.ps1'
if(-not(Test-Path -LiteralPath $implementation -PathType Leaf)){Write-Error 'RED: Resolve-LongRunResume.ps1 is missing.';exit 1}
function Assert-Equal{param($Actual,$Expected,[string]$Message);if($Actual-ne$Expected){throw "$Message Expected=[$Expected] Actual=[$Actual]"}}
function Assert-Contains{param([object[]]$Actual,[string]$Expected,[string]$Message);if($Actual-notcontains$Expected){throw "$Message Missing=[$Expected] Actual=[$($Actual-join ',')]"}}
function Invoke-Resume{param([hashtable]$Arguments);$old=$ErrorActionPreference;$ErrorActionPreference='Continue';try{$raw=&powershell.exe -NoProfile -ExecutionPolicy Bypass -File $implementation @Arguments 2>&1;$code=$LASTEXITCODE}finally{$ErrorActionPreference=$old};$lines=@($raw|ForEach-Object{[string]$_});$start=-1;$end=-1;for($i=0;$i-lt$lines.Count;$i++){if($start-lt 0-and$lines[$i].TrimStart().StartsWith('{')){$start=$i};if($lines[$i].TrimEnd().EndsWith('}')){$end=$i}};$json=if($start-ge 0-and$end-ge$start){(($lines[$start..$end]-join [Environment]::NewLine)|ConvertFrom-Json)}else{$null};[pscustomobject]@{Code=$code;Json=$json}}
function Write-Json{param([string]$Path,$Object);$Object|ConvertTo-Json -Depth 12|Set-Content -LiteralPath $Path -Encoding utf8}
function New-Fixture{param([string]$Root);$cp=Join-Path $Root 'checkpoints';New-Item -ItemType Directory -Path $cp -Force|Out-Null;$manifest=[ordered]@{schema_version=1;run_id='resume-fixture';project_root=$Root;profile_path=(Join-Path $Root 'execution-profile.json');design_hash=('A'*64);plan_hash=('B'*64);model='gpt-5.6-luna';reasoning='xhigh';state='RUNNING';git=[ordered]@{head=('1'*40);branch='codex/fixture';worktree=$Root}};Write-Json -Path (Join-Path $Root 'run-manifest.json') -Object $manifest;$identity=[ordered]@{run_id='resume-fixture';design_hash=('A'*64);plan_hash=('B'*64);model='gpt-5.6-luna';reasoning='xhigh';profile_path=(Join-Path $Root 'execution-profile.json');git_head=('1'*40);writer_state='inactive';active_run_id='resume-fixture'};Write-Json -Path (Join-Path $Root 'identity.json') -Object $identity;$checkpoint=[ordered]@{schema_version=1;run_id='resume-fixture';sequence=1;task_id='T01';checkpoint_sha256='hash-one';previous_checkpoint_sha256=$null};Write-Json -Path (Join-Path $cp 'checkpoint-001.json') -Object $checkpoint;return [pscustomobject]@{Manifest=(Join-Path $Root 'run-manifest.json');Identity=(Join-Path $Root 'identity.json');Checkpoints=$cp;Root=$Root}}
$base=[System.IO.Path]::GetFullPath('X:\Projects\01_Active\15_项目开发治理Skills\99_Temp\long-run-v1_1\T08');$fixture=Join-Path $base ('resume-'+[guid]::NewGuid().ToString('N'));$f=New-Fixture -Root $fixture
try{
    $ok=Invoke-Resume -Arguments @{ManifestPath=$f.Manifest;CheckpointDirectory=$f.Checkpoints;CurrentIdentityPath=$f.Identity;OutputPath=(Join-Path $f.Root 'resume.json')};Assert-Equal $ok.Code 0 'Valid resume must exit zero.';Assert-Equal $ok.Json.decision 'RESUME_ALLOWED' 'Valid resume decision.';Assert-Equal $ok.Json.resume_task 'T02' 'Resume next task.'
    Remove-Item -LiteralPath (Join-Path $f.Checkpoints 'checkpoint-001.json') -Force;$none=Invoke-Resume -Arguments @{ManifestPath=$f.Manifest;CheckpointDirectory=$f.Checkpoints;CurrentIdentityPath=$f.Identity;OutputPath=(Join-Path $f.Root 'no-checkpoint.json')};Assert-Equal $none.Code 1 'No checkpoint must not resume.';Assert-Contains @($none.Json.reason_codes) 'NO_CHECKPOINT' 'No checkpoint reason.'
    $first=[ordered]@{schema_version=1;run_id='resume-fixture';sequence=1;task_id='T01';checkpoint_sha256='hash-one';previous_checkpoint_sha256=$null};Write-Json -Path (Join-Path $f.Checkpoints 'checkpoint-001.json') -Object $first;$second=[ordered]@{schema_version=1;run_id='resume-fixture';sequence=2;task_id='T02';checkpoint_sha256='hash-two';previous_checkpoint_sha256='wrong'};Write-Json -Path (Join-Path $f.Checkpoints 'checkpoint-002.json') -Object $second;$broken=Invoke-Resume -Arguments @{ManifestPath=$f.Manifest;CheckpointDirectory=$f.Checkpoints;CurrentIdentityPath=$f.Identity;OutputPath=(Join-Path $f.Root 'broken.json')};Assert-Equal $broken.Code 1 'Broken chain must fail.';Assert-Equal $broken.Json.decision 'EVIDENCE_INVALIDATED' 'Broken chain decision.';Assert-Contains @($broken.Json.reason_codes) 'CHECKPOINT_CHAIN_INVALID' 'Broken chain reason.'
    Remove-Item -LiteralPath (Join-Path $f.Checkpoints 'checkpoint-002.json') -Force
    $identity=Get-Content -LiteralPath $f.Identity -Raw|ConvertFrom-Json;$identity.design_hash=('C'*64);Write-Json -Path $f.Identity -Object $identity;$drift=Invoke-Resume -Arguments @{ManifestPath=$f.Manifest;CheckpointDirectory=$f.Checkpoints;CurrentIdentityPath=$f.Identity;OutputPath=(Join-Path $f.Root 'drift.json')};Assert-Equal $drift.Json.decision 'EVIDENCE_INVALIDATED' 'Identity drift decision.';Assert-Contains @($drift.Json.reason_codes) 'IDENTITY_CHANGED' 'Identity drift reason.'
    $identity.design_hash=('A'*64);$identity.writer_state='active';Write-Json -Path $f.Identity -Object $identity;$active=Invoke-Resume -Arguments @{ManifestPath=$f.Manifest;CheckpointDirectory=$f.Checkpoints;CurrentIdentityPath=$f.Identity;OutputPath=(Join-Path $f.Root 'active.json')};Assert-Equal $active.Json.Code $null 'Decision JSON shape.';Assert-Equal $active.Json.decision 'BLOCKED_CONFLICT' 'Active writer decision.';Assert-Contains @($active.Json.reason_codes) 'ACTIVE_WRITER_PRESENT' 'Active writer reason.'
    $identity.writer_state='unknown';Write-Json -Path $f.Identity -Object $identity;$unknown=Invoke-Resume -Arguments @{ManifestPath=$f.Manifest;CheckpointDirectory=$f.Checkpoints;CurrentIdentityPath=$f.Identity;OutputPath=(Join-Path $f.Root 'unknown.json')};Assert-Equal $unknown.Json.decision 'READ_ONLY_ONLY' 'Unknown writer decision.';Assert-Contains @($unknown.Json.reason_codes) 'WRITER_STATE_UNKNOWN' 'Unknown writer reason.'
    $identity.writer_state='inactive';$identity.active_run_id='other-run';Write-Json -Path $f.Identity -Object $identity;$duplicate=Invoke-Resume -Arguments @{ManifestPath=$f.Manifest;CheckpointDirectory=$f.Checkpoints;CurrentIdentityPath=$f.Identity;OutputPath=(Join-Path $f.Root 'duplicate.json')};Assert-Equal $duplicate.Json.decision 'BLOCKED_CONFLICT' 'Duplicate run decision.';Assert-Contains @($duplicate.Json.reason_codes) 'DUPLICATE_RUN_ID' 'Duplicate reason.'
    $identity.active_run_id='resume-fixture';Write-Json -Path $f.Identity -Object $identity;$manifest=Get-Content -LiteralPath $f.Manifest -Raw|ConvertFrom-Json;$manifest.state='WAIT_HUMAN';Write-Json -Path $f.Manifest -Object $manifest;$terminal=Invoke-Resume -Arguments @{ManifestPath=$f.Manifest;CheckpointDirectory=$f.Checkpoints;CurrentIdentityPath=$f.Identity;OutputPath=(Join-Path $f.Root 'terminal.json')};Assert-Equal $terminal.Json.decision 'COMPLETED_TERMINAL' 'Terminal decision.'
    Write-Output 'TEST_LONG_RUN_RESUME=PASS';exit 0
}finally{if(Test-Path -LiteralPath $fixture){Remove-Item -LiteralPath $fixture -Recurse -Force}}
