[CmdletBinding()]
param()
$ErrorActionPreference='Stop';$implementation=Join-Path $PSScriptRoot 'Resolve-LongRunBlocker.ps1'
if(-not(Test-Path -LiteralPath $implementation -PathType Leaf)){Write-Error 'RED: Resolve-LongRunBlocker.ps1 is missing.';exit 1}
function Assert-Equal{param($Actual,$Expected,[string]$Message);if($Actual-ne$Expected){throw "$Message Expected=[$Expected] Actual=[$Actual]"}}
function Assert-Contains{param([object[]]$Actual,[string]$Expected,[string]$Message);if($Actual-notcontains$Expected){throw "$Message Missing=[$Expected] Actual=[$($Actual-join ',')]"}}
function Invoke-Blocker{param([hashtable]$Arguments);$old=$ErrorActionPreference;$ErrorActionPreference='Continue';try{$raw=&powershell.exe -NoProfile -ExecutionPolicy Bypass -File $implementation @Arguments 2>&1;$code=$LASTEXITCODE}finally{$ErrorActionPreference=$old};$lines=@($raw|ForEach-Object{[string]$_});$start=-1;$end=-1;for($i=0;$i-lt$lines.Count;$i++){if($start-lt 0-and$lines[$i].TrimStart().StartsWith('{')){$start=$i};if($lines[$i].TrimEnd().EndsWith('}')){$end=$i}};$json=if($start-ge 0-and$end-ge$start){(($lines[$start..$end]-join [Environment]::NewLine)|ConvertFrom-Json)}else{$null};[pscustomobject]@{Code=$code;Json=$json;Raw=$raw}}
function New-Case{param([string]$Root,[string]$Category,[string]$Mitigation,[object]$Attempts,[int]$CleanupRound=0);$failure=Join-Path $Root 'failure.json';$history=Join-Path $Root 'attempts.json';[ordered]@{category=$Category;command='pwsh -File failing.ps1';exit_code=1;mitigation=$Mitigation;evidence=@('evidence/failure.txt');cleanup_round=$CleanupRound;impact='fixture'}|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $failure -Encoding utf8;$historyText=if($null -eq $Attempts -or @($Attempts).Count -eq 0){'[]'}else{$Attempts|ConvertTo-Json -Depth 8};Set-Content -LiteralPath $history -Value $historyText -Encoding utf8;return [pscustomobject]@{Failure=$failure;History=$history}}
$base=[System.IO.Path]::GetFullPath('X:\Projects\01_Active\15_项目开发治理Skills\99_Temp\long-run-v1_1\T09');$fixture=Join-Path $base ('blocker-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Path $fixture -Force|Out-Null
try{
    $trans=New-Case -Root $fixture -Category 'transient' -Mitigation 'clear bounded cache' -Attempts @();$r=Invoke-Blocker -Arguments @{FailurePath=$trans.Failure;AttemptHistoryPath=$trans.History;OutputPath=(Join-Path $fixture 'transient.json')};if($r.Code -ne 0){throw "Transient raw: $($r.Raw -join ' | ')"};Assert-Equal $r.Code 0 'Mitigated transient failure may retry.';Assert-Equal $r.Json.decision 'RETRYABLE' 'Transient decision.';Assert-Equal $r.Json.effective_retry_count 1 'Effective retry count.'
    $noChange=New-Case -Root $fixture -Category 'transient' -Mitigation '' -Attempts @([ordered]@{command='pwsh -File failing.ps1';effective=$true;mitigation='clear bounded cache'});$r=Invoke-Blocker -Arguments @{FailurePath=$noChange.Failure;AttemptHistoryPath=$noChange.History;OutputPath=(Join-Path $fixture 'no-change.json')};Assert-Equal $r.Code 1 'No-change retry must fail.';Assert-Contains @($r.Json.reason_codes) 'NO_CHANGE_RETRY_REJECTED' 'No-change reason.'
    $limit=New-Case -Root $fixture -Category 'transient' -Mitigation 'new mitigation' -Attempts @([ordered]@{command='pwsh -File failing.ps1';effective=$true;mitigation='m1'},[ordered]@{command='pwsh -File failing.ps1';effective=$true;mitigation='m2'});$r=Invoke-Blocker -Arguments @{FailurePath=$limit.Failure;AttemptHistoryPath=$limit.History;OutputPath=(Join-Path $fixture 'limit.json')};Assert-Equal $r.Code 1 'Retry limit must stop.';Assert-Contains @($r.Json.reason_codes) 'RETRY_LIMIT_REACHED' 'Retry limit reason.'
    foreach($pair in @(@('dependency','BLOCKED_DEPENDENCY'),@('conflict','BLOCKED_CONFLICT'),@('external','BLOCKED_EXTERNAL'),@('human','BLOCKED_HUMAN'),@('destructive','BLOCKED_DESTRUCTIVE'),@('model','MODEL_POLICY_BLOCKED'))){$c=New-Case -Root $fixture -Category $pair[0] -Mitigation 'not allowed' -Attempts @();$r=Invoke-Blocker -Arguments @{FailurePath=$c.Failure;AttemptHistoryPath=$c.History;OutputPath=(Join-Path $fixture ($pair[0]+'.json'))};Assert-Equal $r.Code 1 "$($pair[0]) must block.";Assert-Equal $r.Json.decision $pair[1] "$($pair[0]) decision."}
    $c1=New-Case -Root $fixture -Category 'unfinished' -Mitigation '' -Attempts @() -CleanupRound 1;$r=Invoke-Blocker -Arguments @{FailurePath=$c1.Failure;AttemptHistoryPath=$c1.History;OutputPath=(Join-Path $fixture 'cleanup1.json')};Assert-Equal $r.Code 0 'Cleanup round one may proceed.';Assert-Equal $r.Json.decision 'CLEANUP_ROUND_1' 'Cleanup round one decision.'
    $c2=New-Case -Root $fixture -Category 'unfinished' -Mitigation 'dependency resolved' -Attempts @() -CleanupRound 2;$r=Invoke-Blocker -Arguments @{FailurePath=$c2.Failure;AttemptHistoryPath=$c2.History;OutputPath=(Join-Path $fixture 'cleanup2.json')};Assert-Equal $r.Json.decision 'CLEANUP_ROUND_2' 'Cleanup round two decision.'
    $c3=New-Case -Root $fixture -Category 'unfinished' -Mitigation '' -Attempts @() -CleanupRound 3;$r=Invoke-Blocker -Arguments @{FailurePath=$c3.Failure;AttemptHistoryPath=$c3.History;OutputPath=(Join-Path $fixture 'cleanup3.json')};Assert-Equal $r.Code 1 'After round two must stop.';Assert-Equal $r.Json.decision 'CLEANUP_FINISHED_BLOCKED' 'Cleanup finite decision.'
    Write-Output 'TEST_LONG_RUN_BLOCKER=PASS';exit 0
}finally{if(Test-Path -LiteralPath $fixture){Remove-Item -LiteralPath $fixture -Recurse -Force}}
