[CmdletBinding()]
param()
$ErrorActionPreference='Stop';$implementation=Join-Path $PSScriptRoot 'Write-LongRunCheckpoint.ps1'
if(-not(Test-Path -LiteralPath $implementation -PathType Leaf)){Write-Error 'RED: Write-LongRunCheckpoint.ps1 is missing.';exit 1}
function Assert-Equal{param($Actual,$Expected,[string]$Message);if($Actual-ne$Expected){throw "$Message Expected=[$Expected] Actual=[$Actual]"}}
function Assert-Contains{param([object[]]$Actual,[string]$Expected,[string]$Message);if($Actual-notcontains$Expected){throw "$Message Missing=[$Expected] Actual=[$($Actual-join ',')]"}}
function Invoke-Checkpoint{param([hashtable]$Arguments);$old=$ErrorActionPreference;$ErrorActionPreference='Continue';try{$raw=&powershell.exe -NoProfile -ExecutionPolicy Bypass -File $implementation @Arguments 2>&1;$code=$LASTEXITCODE}finally{$ErrorActionPreference=$old};$lines=@($raw|ForEach-Object{[string]$_});$start=-1;$end=-1;for($i=0;$i-lt$lines.Count;$i++){if($start-lt 0-and$lines[$i].TrimStart().StartsWith('{')){$start=$i};if($lines[$i].TrimEnd().EndsWith('}')){$end=$i}};$json=if($start-ge 0-and$end-ge$start){(($lines[$start..$end]-join [Environment]::NewLine)|ConvertFrom-Json)}else{$null};[pscustomobject]@{Code=$code;Json=$json}}
function New-Scenario{param([string]$Root);New-Item -ItemType Directory -Path $Root,(Join-Path $Root 'checkpoints'),(Join-Path $Root 'evidence') -Force|Out-Null;$manifestPath=Join-Path $Root 'run-manifest.json';$evidence=Join-Path $Root 'evidence\task-T01.txt';Set-Content -LiteralPath $evidence -Value 'checkpoint evidence' -Encoding utf8;[ordered]@{schema_version=1;run_id='checkpoint-fixture';project_root=$Root;profile_path=(Join-Path $Root '.codex\long-run\execution-profile.json');design_hash=('A'*64);plan_hash=('B'*64);model='gpt-5.6-luna';reasoning='xhigh';git=[ordered]@{root=$Root;worktree=$Root;branch='codex/fixture';head=('1'*40)}}|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $manifestPath -Encoding utf8;return [pscustomobject]@{Root=$Root;Manifest=$manifestPath;Evidence=$evidence;Checkpoints=(Join-Path $Root 'checkpoints')}}
$base=[System.IO.Path]::GetFullPath('X:\Projects\01_Active\15_项目开发治理Skills\99_Temp\long-run-v1_1\T07');$fixture=Join-Path $base ('checkpoint-'+[guid]::NewGuid().ToString('N'));$s=New-Scenario -Root $fixture;$outside=$null
try{
    $one=Invoke-Checkpoint -Arguments @{ManifestPath=$s.Manifest;TaskId='T01';Command='pwsh -File tests.ps1';ExitCode=0;EvidencePath=$s.Evidence;OutputPath=(Join-Path $s.Checkpoints 'checkpoint-001.json')};if($one.Code -ne 0){throw "First raw: $($one.Raw -join ' | ')"};Assert-Equal $one.Code 0 'First checkpoint must succeed.';Assert-Equal $one.Json.valid $true 'First checkpoint valid.';Assert-Equal $one.Json.checkpoint.sequence 1 'First sequence.';Assert-Equal $one.Json.checkpoint.previous_checkpoint_sha256 $null 'First previous hash empty.'
    $two=Invoke-Checkpoint -Arguments @{ManifestPath=$s.Manifest;TaskId='T02';Command='pwsh -File tests-2.ps1';ExitCode=0;EvidencePath=$s.Evidence;OutputPath=(Join-Path $s.Checkpoints 'checkpoint-002.json')};Assert-Equal $two.Code 0 'Second checkpoint must succeed.';Assert-Equal $two.Json.checkpoint.sequence 2 'Second sequence.';Assert-Equal $two.Json.checkpoint.previous_checkpoint_sha256 $one.Json.checkpoint.checkpoint_sha256 'Hash chain continuity.'
    $exists=Invoke-Checkpoint -Arguments @{ManifestPath=$s.Manifest;TaskId='T02';Command='same';ExitCode=0;EvidencePath=$s.Evidence;OutputPath=(Join-Path $s.Checkpoints 'checkpoint-002.json')};Assert-Equal $exists.Code 1 'Existing checkpoint must be protected.';Assert-Contains @($exists.Json.reason_codes) 'OUTPUT_EXISTS' 'Output protection reason.'
    $missing=Invoke-Checkpoint -Arguments @{ManifestPath=$s.Manifest;TaskId='T03';Command='missing';ExitCode=1;EvidencePath=(Join-Path $s.Root 'evidence\missing.txt');OutputPath=(Join-Path $s.Checkpoints 'checkpoint-003.json')};Assert-Equal $missing.Code 1 'Missing evidence must fail.';Assert-Contains @($missing.Json.reason_codes) 'EVIDENCE_MISSING' 'Evidence reason.'
    $outside=Join-Path 'E:\iwen-codex\codex-study\.codex-tmp\preflight' ('outside-evidence-'+[guid]::NewGuid().ToString('N')+'.txt');New-Item -ItemType Directory -Path (Split-Path -Parent $outside) -Force|Out-Null;Set-Content -LiteralPath $outside -Value 'outside' -Encoding utf8;$out=Invoke-Checkpoint -Arguments @{ManifestPath=$s.Manifest;TaskId='T03';Command='outside';ExitCode=0;EvidencePath=$outside;OutputPath=(Join-Path $s.Checkpoints 'checkpoint-003.json')};Assert-Equal $out.Code 1 'Outside evidence must fail.';Assert-Contains @($out.Json.reason_codes) 'EVIDENCE_OUTSIDE_PROJECT_ROOT' 'Outside evidence reason.'
    $badTask=Invoke-Checkpoint -Arguments @{ManifestPath=$s.Manifest;TaskId='X';Command='bad task';ExitCode=0;EvidencePath=$s.Evidence;OutputPath=(Join-Path $s.Checkpoints 'checkpoint-003.json')};Assert-Equal $badTask.Code 1 'Invalid task ID must fail.';Assert-Contains @($badTask.Json.reason_codes) 'TASK_ID_INVALID' 'Task ID reason.'
    $tampered=Get-Content -LiteralPath (Join-Path $s.Checkpoints 'checkpoint-002.json') -Raw|ConvertFrom-Json;$tampered.checkpoint_sha256='BAD';$tampered|ConvertTo-Json -Depth 12|Set-Content -LiteralPath (Join-Path $s.Checkpoints 'checkpoint-002.json') -Encoding utf8;$chain=Invoke-Checkpoint -Arguments @{ManifestPath=$s.Manifest;TaskId='T03';Command='chain';ExitCode=0;EvidencePath=$s.Evidence;OutputPath=(Join-Path $s.Checkpoints 'checkpoint-003.json')};Assert-Equal $chain.Code 1 'Tampered chain must fail.';Assert-Contains @($chain.Json.reason_codes) 'CHECKPOINT_CHAIN_INVALID' 'Chain reason.'
    Write-Output 'TEST_LONG_RUN_CHECKPOINT=PASS';exit 0
}finally{if(Test-Path -LiteralPath $fixture){Remove-Item -LiteralPath $fixture -Recurse -Force};if($outside -and (Test-Path -LiteralPath $outside)){Remove-Item -LiteralPath $outside -Force}}
