[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
function Assert-True { param([bool]$Condition, [string]$Message); if(-not $Condition){throw "ASSERTION_FAILED: $Message"} }
function Assert-Equal { param($Actual,$Expected,[string]$Message); if($Actual -ne $Expected){throw "ASSERTION_FAILED: $Message (expected '$Expected', got '$Actual')"} }
function Assert-Contains { param([object[]]$Values,[string]$Expected,[string]$Message); Assert-True (@($Values|ForEach-Object{[string]$_}) -contains $Expected) "$Message (missing '$Expected')" }
function Read-Json { param([string]$Path); Assert-True (Test-Path -LiteralPath $Path -PathType Leaf) "Missing JSON: $Path"; return Get-Content -LiteralPath $Path -Raw -Encoding UTF8|ConvertFrom-Json }
function Write-Json { param([string]$Path,$Object); $Object|ConvertTo-Json -Depth 30|Set-Content -LiteralPath $Path -Encoding UTF8 }
function Invoke-Tool { param([string]$InputPath,[string]$OutputPath); $raw=@(& $resolverPath -InputPath $InputPath -OutputPath $OutputPath 2>&1); $e=$LASTEXITCODE; $j=$null;if($raw.Count -gt 0){try{$j=(($raw|ForEach-Object{[string]$_})-join [Environment]::NewLine)|ConvertFrom-Json}catch{}}; return [pscustomobject]@{ExitCode=$e;Json=$j;Raw=$raw} }
function New-CandidateSource {
    $planning=@(Get-ChildItem -LiteralPath (Join-Path $root 'docs\future-development') -File|Where-Object{$_.Name -like '*V1.2.md'}|Sort-Object Length);$branch=((@(& git -C $root branch --show-current)|Select-Object -First 1).Trim());$head=((@(& git -C $root rev-parse HEAD)|Select-Object -First 1).Trim());$dirtyLines=@(& git -C $root status --porcelain);$inputPath=Join-Path $fixtureDir 'impact-candidate-input.json';$candidatePath=Join-Path $fixtureDir 'impact-candidate.json';$obj=[ordered]@{schema_version=1;project_id='fixture-content-media';project_root=$root;worktree=$root;branch=$branch;head=$head;dirty=($dirtyLines.Count -gt 0);design_path=$planning[0].FullName;plan_path=$planning[1].FullName;design_hash=(Get-FileHash $planning[0].FullName -Algorithm SHA256).Hash.ToUpperInvariant();plan_hash=(Get-FileHash $planning[1].FullName -Algorithm SHA256).Hash.ToUpperInvariant();changed_paths=@('src/example.ps1');tests=@([ordered]@{command='test';exit_code=0});artifacts=@();risk_tier='LIGHTWEIGHT';rollback='Restore prior candidate.'};Write-Json $inputPath $obj;$r=@(& $candidateGenerator -InputPath $inputPath -OutputPath $candidatePath 2>&1);if($LASTEXITCODE -ne 0){throw "CANDIDATE_SOURCE_FAILED: $($r -join ' ')"};return Read-Json $candidatePath
}

$root=Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot));$resolverPath=Join-Path $PSScriptRoot 'Resolve-AffectedReviewScope.ps1';$candidateGenerator=Join-Path $PSScriptRoot 'New-LightweightCandidateManifest.ps1';$fixtureBase=Join-Path $root 'outputs\skill-packaging\lightweight-governance-v1_2\T04\test-fixtures';$fixtureDir=Join-Path $fixtureBase ('run-' + [guid]::NewGuid().ToString('N'))
try {
    Assert-True (Test-Path -LiteralPath $resolverPath -PathType Leaf) 'impact resolver must exist'
    Assert-True (Test-Path -LiteralPath $candidateGenerator -PathType Leaf) 'candidate generator must exist'
    New-Item -ItemType Directory -Path $fixtureDir -Force|Out-Null;$candidate=New-CandidateSource;$candidatePath=Join-Path $fixtureDir 'impact-candidate.json'
    $common=[ordered]@{schema_version=1;candidate_manifest_path=$candidatePath;candidate_sha256=$candidate.candidate_sha256;changed_paths=@('src/example.ps1');test_mappings=@([ordered]@{path_prefix='src/';tests=@('tests/example.Tests.ps1');evidence=@('evidence/src.txt')});evidence_references=@([ordered]@{id='src-evidence';path='evidence/src.txt';depends_on=@('src/example.ps1')},[ordered]@{id='unrelated-evidence';path='evidence/unrelated.txt';depends_on=@('docs/unrelated.md')});configuration_dependencies=@([ordered]@{path_prefix='config/';scope='project'})}
    $inputPath=Join-Path $fixtureDir 'impact-valid-input.json';$outputPath=Join-Path $fixtureDir 'impact-valid.json';Write-Json $inputPath $common;$valid=Invoke-Tool $inputPath $outputPath;Assert-Equal $valid.ExitCode 0 'valid impact must exit 0';$impact=Read-Json $outputPath;Assert-Contains @($impact.affected_tests) 'tests/example.Tests.ps1' 'mapped test';Assert-Contains @($impact.invalidated_evidence) 'src-evidence' 'affected evidence';Assert-Contains @($impact.retained_evidence) 'unrelated-evidence' 'unrelated evidence retained';Assert-Equal $impact.expanded $false 'small source change must not expand';Write-Output 'PASS impact_path_test_evidence_mapping'
    $again=Invoke-Tool $inputPath $outputPath;Assert-Equal $again.ExitCode 1 'impact output must be create-only';Assert-Contains @($again.Json.reason_codes) 'OUTPUT_EXISTS' 'impact create-only reason';Write-Output 'PASS impact_create_only'

    $noImpact=[ordered]@{};foreach($p in $common.GetEnumerator()){$noImpact[$p.Key]=$p.Value};$noImpact.changed_paths=@('docs/other.md');$noPath=Join-Path $fixtureDir 'impact-no-change-input.json';$noOut=Join-Path $fixtureDir 'impact-no-change.json';Write-Json $noPath $noImpact;$no=Invoke-Tool $noPath $noOut;Assert-Equal $no.ExitCode 0 'no-impact evidence must still exit 0';$noManifest=Read-Json $noOut;Assert-Contains @($noManifest.retained_evidence) 'unrelated-evidence' 'no-impact evidence retained';Assert-Contains @($noManifest.reason_codes) 'NO_AFFECTED_EVIDENCE_INVALIDATION' 'no-impact reason';Write-Output 'PASS no_impact_evidence_retained'
    $config=[ordered]@{};foreach($p in $common.GetEnumerator()){$config[$p.Key]=$p.Value};$config.changed_paths=@('config/lightweight-governance/projects.json');$configOut=Join-Path $fixtureDir 'impact-config-change.json';$configIn=Join-Path $fixtureDir 'impact-config-input.json';Write-Json $configIn $config;$configResult=Invoke-Tool $configIn $configOut;Assert-Equal $configResult.ExitCode 0 'config impact must exit 0';$configManifest=Read-Json $configOut;$expectedExpanded=$true;Assert-Equal $configManifest.expanded $expectedExpanded 'config change must expand';Assert-Contains @($configManifest.reason_codes) 'CONFIG_OR_SCHEMA_CHANGE' 'config expansion reason';Write-Output 'PASS config_dependency_expands_scope'
    $drift=[ordered]@{};foreach($p in $common.GetEnumerator()){$drift[$p.Key]=$p.Value};$drift.candidate_sha256=('0'*64);$driftIn=Join-Path $fixtureDir 'impact-candidate-drift-input.json';$driftOut=Join-Path $fixtureDir 'impact-candidate-drift.json';Write-Json $driftIn $drift;$driftResult=Invoke-Tool $driftIn $driftOut;Assert-Equal $driftResult.ExitCode 1 'candidate drift must block';Assert-Contains @($driftResult.Json.reason_codes) 'CANDIDATE_HASH_MISMATCH' 'candidate drift reason';Write-Output 'PASS upstream_candidate_change_invalidates_scope'
    Write-Output 'AFFECTED_REVIEW_SCOPE_TESTS=PASS';exit 0
} catch {Write-Error $_.Exception.Message;Write-Output 'AFFECTED_REVIEW_SCOPE_TESTS=FAIL';exit 1}
