[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

function Assert-True { param([bool]$Condition, [string]$Message); if (-not $Condition) { throw "ASSERTION_FAILED: $Message" } }
function Assert-Equal { param($Actual, $Expected, [string]$Message); if ($Actual -ne $Expected) { throw "ASSERTION_FAILED: $Message (expected '$Expected', got '$Actual')" } }
function Assert-Contains { param([object[]]$Values, [string]$Expected, [string]$Message); Assert-True (@($Values | ForEach-Object { [string]$_ }) -contains $Expected) "$Message (missing '$Expected')" }
function Write-Json { param([string]$Path, $Object); $Object | ConvertTo-Json -Depth 30 | Set-Content -LiteralPath $Path -Encoding UTF8 }
function Invoke-Resolver { param([string]$InputPath); $raw=@(& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $scriptPath -InputPath $InputPath 2>&1);$exitCode=$LASTEXITCODE;$json=$null;if($raw.Count -gt 0){try{$json=(($raw|ForEach-Object{[string]$_})-join [Environment]::NewLine)|ConvertFrom-Json}catch{}};return [pscustomobject]@{ExitCode=$exitCode;Json=$json;Raw=$raw} }
function New-Input { param([string]$Name, [string[]]$Triggers, [hashtable]$Signals, [string[]]$Approvals, [string[]]$Evidence, [hashtable]$Qualification, [string]$Activity='ordinary_code', [string]$CandidateStatus='', [string]$FinalReviewDecision='');$path=Join-Path $fixtureDir ($Name+'.json');$input=[ordered]@{schema_version=1;project_id='fixture-lightweight-governance';project_type='personal_tool';activity=$Activity;hard_triggers=@($Triggers);signals=$Signals;approvals=@($Approvals);evidence=@($Evidence);qualification=$Qualification;candidate_status=$CandidateStatus;final_review_decision=$FinalReviewDecision;changed_paths=@('skills/lightweight-project-governance/scripts/example.ps1')};Write-Json $path $input;return $path }

$root=Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot));$scriptPath=Join-Path $PSScriptRoot 'Resolve-EscalatedGovernanceGates.ps1';$fixtureBase=Join-Path $root 'outputs\skill-packaging\lightweight-governance-v1_2\T06\test-fixtures';$fixtureDir=Join-Path $fixtureBase ('run-' + [guid]::NewGuid().ToString('N'))
try {
    Assert-True (Test-Path -LiteralPath $scriptPath -PathType Leaf) 'escalation resolver must exist'
    New-Item -ItemType Directory -Path $fixtureDir -Force|Out-Null
    $none=[ordered]@{legal=$false;license=$false;account_permission=$false;designated_role=$false}

    $ordinaryInput=New-Input -Name 'ordinary-personal-tool' -Triggers @() -Signals @{personal_tool=$true} -Approvals @() -Evidence @('ENGINEERING_TESTS') -Qualification $none -CandidateStatus 'PASS' -FinalReviewDecision '通过';$ordinary=Invoke-Resolver $ordinaryInput;Assert-Equal $ordinary.ExitCode 0 'ordinary personal tool exits 0';Assert-Equal $ordinary.Json.verdict 'LIGHTWEIGHT_ALLOWED' 'ordinary personal tool verdict';Assert-Equal $ordinary.Json.qualification_review 'not_required' 'ordinary qualification not required';Assert-Equal @($ordinary.Json.required_approvals).Count 0 'ordinary tool has no approvals';Assert-True (@($ordinary.Json.required_approvals) -notcontains 'BUSINESS_OWNER') 'ordinary tool no business approval';Assert-True (@($ordinary.Json.required_approvals) -notcontains 'COMPLIANCE_OWNER') 'ordinary tool no compliance approval';Assert-True (@($ordinary.Json.required_approvals) -notcontains 'SECOND_REVIEWER') 'ordinary tool no second reviewer';Write-Output 'PASS ordinary_personal_tool_minimal_gates'

    $formalMissingInput=New-Input -Name 'formal-data-missing' -Triggers @('formal_data') -Signals @{} -Approvals @() -Evidence @() -Qualification $none -CandidateStatus 'PASS' -FinalReviewDecision '通过';$formalMissing=Invoke-Resolver $formalMissingInput;Assert-Equal $formalMissing.ExitCode 1 'formal data missing gates fail closed';Assert-Equal $formalMissing.Json.verdict 'BLOCKED_ESCALATION' 'formal data blocked verdict';Assert-Contains @($formalMissing.Json.required_approvals) 'BUSINESS_OWNER' 'formal data business approval';Assert-Contains @($formalMissing.Json.required_approvals) 'COMPLIANCE_OWNER' 'formal data compliance approval';Assert-Contains @($formalMissing.Json.required_evidence) 'SOURCE_REGISTER' 'formal data source evidence';Assert-Contains @($formalMissing.Json.reason_codes) 'HARD_TRIGGER_FORMAL_DATA' 'formal data hard trigger';Assert-Contains @($formalMissing.Json.reason_codes) 'ESCALATION_APPROVAL_MISSING' 'formal data approval missing';Assert-Contains @($formalMissing.Json.reason_codes) 'ESCALATION_EVIDENCE_MISSING' 'formal data evidence missing';Write-Output 'PASS formal_data_fail_closed'

    $formalReadyInput=New-Input -Name 'formal-data-ready' -Triggers @('formal_data') -Signals @{} -Approvals @('BUSINESS_OWNER','COMPLIANCE_OWNER') -Evidence @('SOURCE_REGISTER','FACT_VERIFICATION','DATA_PROVENANCE') -Qualification $none;$formalReady=Invoke-Resolver $formalReadyInput;Assert-Equal $formalReady.ExitCode 0 'formal data complete gates exits 0';Assert-Equal $formalReady.Json.verdict 'ESCALATED_READY' 'formal data ready verdict';Assert-Contains @($formalReady.Json.owners) 'BUSINESS_OWNER' 'formal data owner';Assert-Contains @($formalReady.Json.release_criteria) 'FORMAL_DATA_SOURCE_REVIEW' 'formal data release criteria';Assert-Contains @($formalReady.Json.recovery_entry) 'FORMAL_DATA_ROLLBACK' 'formal data recovery';Assert-Equal $formalReady.Json.qualification_review 'not_required' 'formal data qualification remains minimal';Write-Output 'PASS formal_data_ready_mapping'

    $acceptedInput=New-Input -Name 'accepted-fact' -Triggers @('AcceptedFact') -Signals @{} -Approvals @('BUSINESS_OWNER','SOURCE_OWNER') -Evidence @('SOURCE_REGISTER','FACT_VERIFICATION') -Qualification $none -Activity 'formal_fact';$accepted=Invoke-Resolver $acceptedInput;Assert-Equal $accepted.ExitCode 0 'AcceptedFact complete gates exits 0';Assert-Contains @($accepted.Json.reason_codes) 'HARD_TRIGGER_ACCEPTED_FACT' 'AcceptedFact reason';Assert-Contains @($accepted.Json.required_approvals) 'SOURCE_OWNER' 'AcceptedFact source owner';Assert-Contains @($accepted.Json.required_evidence) 'FACT_VERIFICATION' 'AcceptedFact evidence';Write-Output 'PASS accepted_fact_mapping'

    $recommendationInput=New-Input -Name 'formal-recommendation' -Triggers @('formal_recommendation') -Signals @{} -Approvals @('BUSINESS_OWNER','COMPLIANCE_OWNER','RECOMMENDATION_REVIEWER') -Evidence @('SOURCE_TRACE','RECOMMENDATION_CRITERIA','HUMAN_REVIEW') -Qualification $none -Activity 'formal_recommendation';$recommendation=Invoke-Resolver $recommendationInput;Assert-Equal $recommendation.ExitCode 0 'formal recommendation complete gates exits 0';Assert-Contains @($recommendation.Json.required_approvals) 'RECOMMENDATION_REVIEWER' 'recommendation reviewer approval';Assert-Contains @($recommendation.Json.required_evidence) 'SOURCE_TRACE' 'recommendation source evidence';Assert-Contains @($recommendation.Json.recovery_entry) 'RECOMMENDATION_ROLLBACK' 'recommendation recovery';Write-Output 'PASS formal_recommendation_mapping'

    $protectedInput=New-Input -Name 'personal-student-data' -Triggers @('personal_or_student_data') -Signals @{} -Approvals @('DATA_PROTECTION_OWNER','COMPLIANCE_OWNER') -Evidence @('AUTHORIZED_DATA_SCOPE','DATA_MINIMIZATION','ACCESS_LOG') -Qualification $none;$protected=Invoke-Resolver $protectedInput;Assert-Equal $protected.ExitCode 0 'personal student data complete gates exits 0';Assert-Contains @($protected.Json.required_approvals) 'DATA_PROTECTION_OWNER' 'protected data owner';Assert-Contains @($protected.Json.required_evidence) 'AUTHORIZED_DATA_SCOPE' 'protected data authorization';Assert-Contains @($protected.Json.recovery_entry) 'PROTECTED_DATA_DELETE_OR_REVOKE' 'protected data recovery';Write-Output 'PASS personal_student_data_mapping'

    $releaseInput=New-Input -Name 'production-public' -Triggers @('production_or_publication') -Signals @{} -Approvals @('RELEASE_OWNER','BUSINESS_OWNER','COMPLIANCE_OWNER') -Evidence @('RELEASE_CHECKLIST','ROLLBACK_PLAN','OBSERVABILITY') -Qualification $none;$release=Invoke-Resolver $releaseInput;Assert-Equal $release.ExitCode 0 'production public complete gates exits 0';Assert-Contains @($release.Json.required_approvals) 'RELEASE_OWNER' 'release owner approval';Assert-Contains @($release.Json.required_evidence) 'ROLLBACK_PLAN' 'release rollback evidence';Assert-Contains @($release.Json.release_criteria) 'RELEASE_APPROVAL' 'release approval criterion';Write-Output 'PASS production_publication_mapping'

    $accountInput=New-Input -Name 'paid-account' -Triggers @('paid_or_external_account') -Signals @{} -Approvals @('ACCOUNT_OWNER','USER_EXTERNAL_ACTION_APPROVER') -Evidence @('ACCOUNT_AUTHORIZATION','PAYMENT_APPROVAL') -Qualification $none;$account=Invoke-Resolver $accountInput;Assert-Equal $account.ExitCode 0 'paid account complete gates exits 0';Assert-Contains @($account.Json.required_approvals) 'ACCOUNT_OWNER' 'account owner approval';Assert-Contains @($account.Json.required_evidence) 'ACCOUNT_AUTHORIZATION' 'account authorization evidence';Assert-Contains @($account.Json.recovery_entry) 'ACCOUNT_REVOKE_OR_REFUND' 'account recovery';Write-Output 'PASS paid_account_mapping'

    $bypassInput=New-Input -Name 'formal-bypass-attempt' -Triggers @('formal_recommendation') -Signals @{} -Approvals @() -Evidence @() -Qualification $none -CandidateStatus 'PASS' -FinalReviewDecision '通过';$bypass=Invoke-Resolver $bypassInput;Assert-Equal $bypass.ExitCode 1 'engineering and final pass cannot bypass escalation';Assert-Contains @($bypass.Json.reason_codes) 'ESCALATION_APPROVAL_MISSING' 'bypass approval remains blocked';Write-Output 'PASS lightweight_status_cannot_bypass'

    $qualification=[ordered]@{legal=$true;license=$false;account_permission=$false;designated_role=$false};$qualificationInput=New-Input -Name 'qualification-required' -Triggers @() -Signals @{} -Approvals @() -Evidence @('LEGAL_BASIS') -Qualification $qualification;$qualificationResult=Invoke-Resolver $qualificationInput;Assert-Equal $qualificationResult.ExitCode 1 'qualification without owner approval fails closed';Assert-Equal $qualificationResult.Json.qualification_review 'required' 'qualification review required';Assert-Contains @($qualificationResult.Json.required_approvals) 'QUALIFICATION_OWNER' 'qualification owner approval';Assert-Contains @($qualificationResult.Json.reason_codes) 'QUALIFICATION_REVIEW_REQUIRED' 'qualification reason';Write-Output 'PASS qualification_only_when_explicit'

    $unknownInput=New-Input -Name 'unknown-trigger' -Triggers @('mystery_trigger') -Signals @{} -Approvals @() -Evidence @() -Qualification $none;$unknown=Invoke-Resolver $unknownInput;Assert-Equal $unknown.ExitCode 1 'unknown trigger fails closed';Assert-Equal $unknown.Json.verdict 'BLOCKED_ESCALATION' 'unknown trigger blocked';Assert-Contains @($unknown.Json.reason_codes) 'UNKNOWN_HARD_TRIGGER' 'unknown trigger reason';Write-Output 'PASS unknown_trigger_fail_closed'

    $conflictInput=New-Input -Name 'conflicting-signals' -Triggers @() -Signals @{formal_data=$true;conflict=$true} -Approvals @() -Evidence @() -Qualification $none;$conflict=Invoke-Resolver $conflictInput;Assert-Equal $conflict.ExitCode 1 'conflict fails closed';Assert-Contains @($conflict.Json.reason_codes) 'ESCALATION_CONFLICT' 'conflict reason';Write-Output 'PASS conflicting_signals_fail_closed'

    Write-Output 'ESCALATED_GOVERNANCE_GATES_TESTS=PASS';exit 0
} catch {Write-Error $_.Exception.Message;Write-Output 'ESCALATED_GOVERNANCE_GATES_TESTS=FAIL';exit 1}
